<a href="https://colab.research.google.com/github/thippeshms/thippeshms/blob/main/Medical_Insurance_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/insurance.csv')
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [ ]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
df.duplicated().sum()

1

In [ ]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [ ]:
df.replace({'sex':{'male':1,'female':0},'smoker':{'yes':1,'no':0},'region':{'southwest':0,'southeast':1,'northwest':2,'northeast':3}},inplace=True)


In [ ]:
df

age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       0  16884.92400
1      18    1  33.770         1       0       1   1725.55230
2      28    1  33.000         3       0       1   4449.46200
3      33    1  22.705         0       0       2  21984.47061
4      32    1  28.880         0       0       2   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       2  10600.54830
1334   18    0  31.920         0       0       3   2205.98080
1335   18    0  36.850         0       0       1   1629.83350
1336   21    0  25.800         0       0       0   2007.94500
1337   61    0  29.070         0       1       2  29141.36030

[1338 rows x 7 columns]

In [ ]:
x=df.drop(['charges'],axis=1)
y=df['charges']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train.shape

(1070, 6)

In [ ]:
x_test.shape

(268, 6)

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(x_test)
y_pred

array([ 1.10172305e+04,  9.78753017e+03,  3.79947821e+04,  1.61227784e+04,
        6.93075923e+03,  3.96902046e+03,  1.55178430e+03,  1.42832091e+04,
        8.95342886e+03,  7.43194558e+03,  4.54457668e+03,  1.02472753e+04,
        8.65710757e+03,  4.12619770e+03,  2.78113171e+04,  1.10395971e+04,
        1.12514458e+04,  6.03101003e+03,  8.17339252e+03,  2.70394424e+04,
        3.35778484e+04,  1.42670864e+04,  1.16850232e+04,  3.24069403e+04,
        4.41465153e+03,  9.14607182e+03,  1.12786921e+03,  1.00891473e+04,
        4.08782973e+03,  1.03569127e+04,  8.96224058e+03,  4.02452861e+04,
        1.54779185e+04,  1.36671353e+04,  2.47415217e+04,  5.13005676e+03,
        1.28428861e+04,  3.05264017e+04,  3.34289155e+04,  3.48813457e+03,
        4.00215674e+03,  4.27800724e+03,  3.04613664e+04,  3.93491672e+04,
        2.80033682e+04,  5.00299253e+03,  1.09312243e+04,  7.77848493e+03,
        3.60829639e+03,  1.05573586e+04,  5.62958594e+03,  3.37882569e+03,
        3.28476568e+04,  

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
knr = KNeighborsRegressor()
knr.fit(x_train,y_train)

KNeighborsRegressor()

In [ ]:
kn_pred = knr.predict(x_test)
kn_pred

array([13254.721394,  8520.40641 , 16314.91865 , 16692.404402,
       11625.0915  ,  8527.687302,  4753.20957 , 25161.975932,
        6618.21862 ,  5195.89413 , 13324.24568 , 16619.632168,
        7249.0648  , 13527.037602,  8895.09321 , 16423.250828,
       12470.20143 ,  6551.358412,  6252.69581 ,  1883.58108 ,
       25185.535268, 12571.26232 , 13524.213774, 14726.229964,
        1758.31414 , 17220.414906, 10678.31446 ,  7289.3936  ,
        6756.40649 , 32045.499054, 11695.547676, 19130.56423 ,
       20526.93282 , 10660.26324 ,  6814.095078,  4175.81353 ,
       22324.30886 , 18468.279574, 13921.79318 ,  6016.679606,
        6453.55266 ,  6800.53393 ,  9824.68074 , 19376.65764 ,
       15503.95245 ,  3098.13495 , 16423.250828, 16299.090264,
       11553.0781  , 11719.68082 ,  2936.21456 , 14370.764836,
       14493.392572, 25769.109232, 18778.42271 , 20083.338036,
       10050.67146 , 12621.103912,  9122.18249 , 12624.48419 ,
        4693.501   , 26761.103276, 24753.288352, 16922.

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7998747145449959

In [ ]:
r2_score(y_test,kn_pred)#so we can tell knregreesion wont work properly for this data bc of less percentage

0.22490923629662052

In [ ]:
import numpy as np
input_data=(19,0,27.900,0,1,0)
convert_to_array=np.asarray(input_data)
re_shape=convert_to_array.reshape(1, -1)
prediction=lr.predict(re_shape)
print(prediction)

[25029.64806821]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [ ]:
lr.coef_

array([  253.99185244,   -24.32455098,   328.40261701,   443.72929547,
       23568.87948381,   288.50857254])

In [ ]:
lr.intercept_

-12527.509626455563

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [ ]:
steps=[('Standard_Scaler', StandardScaler()),
         ('Regression',LinearRegression())]

In [ ]:
pipe=Pipeline(steps)
pipe

Pipeline(steps=[('Standard_Scaler', StandardScaler()),
                ('Regression', LinearRegression())])

In [ ]:
pipe

Pipeline(steps=[('Standard_Scaler', StandardScaler()),
                ('Regression', LinearRegression())])

In [ ]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('Standard_Scaler', StandardScaler()),
                ('Regression', LinearRegression())])

In [ ]:
pipe.predict(x_test)

array([ 1.10172305e+04,  9.78753017e+03,  3.79947821e+04,  1.61227784e+04,
        6.93075923e+03,  3.96902046e+03,  1.55178430e+03,  1.42832091e+04,
        8.95342886e+03,  7.43194558e+03,  4.54457668e+03,  1.02472753e+04,
        8.65710757e+03,  4.12619770e+03,  2.78113171e+04,  1.10395971e+04,
        1.12514458e+04,  6.03101003e+03,  8.17339252e+03,  2.70394424e+04,
        3.35778484e+04,  1.42670864e+04,  1.16850232e+04,  3.24069403e+04,
        4.41465153e+03,  9.14607182e+03,  1.12786921e+03,  1.00891473e+04,
        4.08782973e+03,  1.03569127e+04,  8.96224058e+03,  4.02452861e+04,
        1.54779185e+04,  1.36671353e+04,  2.47415217e+04,  5.13005676e+03,
        1.28428861e+04,  3.05264017e+04,  3.34289155e+04,  3.48813457e+03,
        4.00215674e+03,  4.27800724e+03,  3.04613664e+04,  3.93491672e+04,
        2.80033682e+04,  5.00299253e+03,  1.09312243e+04,  7.77848493e+03,
        3.60829639e+03,  1.05573586e+04,  5.62958594e+03,  3.37882569e+03,
        3.28476568e+04,  

In [ ]:
from sklearn.decomposition import PCA

step2=[("Standard_Scaler",StandardScaler()),
        ("PCA",PCA(n_components=3)),
       ("Regression",LinearRegression())]

In [ ]:
pipe2=Pipeline(step2)
pipe2

Pipeline(steps=[('Standard_Scaler', StandardScaler()),
                ('PCA', PCA(n_components=3)),
                ('Regression', LinearRegression())])

In [ ]:
pipe2.fit(x_train,y_train)

Pipeline(steps=[('Standard_Scaler', StandardScaler()),
                ('PCA', PCA(n_components=3)),
                ('Regression', LinearRegression())])

In [ ]:
pipe2.predict(x_test)

array([14858.46198658,  7974.78107262, 28475.83290755, 14474.92399252,
        5145.29252125, 11607.77530337,  3471.20934496, 15653.67727108,
       14085.25630835, 20586.73300372, 13643.2920091 , 11786.29811452,
        6982.55077568,  3307.94325107, 19627.43353423, 14329.4154336 ,
       13428.18111846, 14745.5149887 , 17995.39307715, 19833.81150792,
       27665.58589551, 12833.99419092,  6783.13827448, 13610.74366345,
       10042.95910596, 15605.40156773,  3738.63952177, 13776.69206388,
        3228.89330954, 18697.45127128, 14158.17091241, 25724.51250284,
       13145.79711592, 12521.11234448, 12432.86777962,  4640.50639006,
       18633.6326927 , 21989.82001049, 20177.59209586,  2098.03331056,
        4619.63118835, 10263.39330776, 21219.45252982, 29112.40588953,
       11665.90308226,  9666.94126717, 14306.91919616, 15061.53842019,
        7318.66650215,  8490.01071329,  4495.40049846, 12252.75820651,
       23182.52488301, 25201.40902836,  6714.41304443, 12036.65044764,
      

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
categorical_processor = Pipeline(
steps=[("imputation_mean", SimpleImputer(fill_value='missing', strategy="constant")),
        ("onehotencoding", OneHotEncoder())]
)

In [ ]:
import numpy as np
numeric_process=Pipeline(
steps=[("imputation_mean", SimpleImputer(missing_values=np.nan,strategy='mean')),
       ("scaler",StandardScaler())]
)

In [ ]:
categorical_processor

Pipeline(steps=[('imputation_mean',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehotencoding', OneHotEncoder())])

In [ ]:
numeric_process

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [ ]:
from sklearn.compose import ColumnTransformer
preprocessor=ColumnTransformer([
    ("categorical",categorical_processor,['sex','region']),
    ("numerica_process", numeric_process,['charges','bmi'])
])

In [ ]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehotencoding',
                                                  OneHotEncoder())]),
                                 ['sex', 'region']),
                                ('numerica_process',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['charges', 'bmi'])])